# Generated by Django 5.2.6 on 2025-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descipcion', models.TextField(max_length=200)),
                ('foto', models.ImageField(upload_to='equipo_trabajo', verbose_name='Imagen')),
            ],
        ),
    ]
