# Generated by Django 5.2.6 on 2025-10-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='create',
            field=models.DateField(auto_created=True, default='2025-10-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
