# Generated by Django 5.2.6 on 2025-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_equipo_create_equipo_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
