# Generated by Django 5.2.6 on 2025-10-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_alter_equipo_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='update',
            new_name='updatea',
        ),
    ]
