# Generated by Django 5.2.6 on 2025-11-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(choices=[('Concepcion', 'concepcion'), ('San Pedro', 'san pedro'), ('Hualpen', 'hualpen')], default='Concepcion')),
                ('telefono', models.IntegerField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField(max_length=10)),
                ('descripcion', models.TextField(max_length=200)),
                ('foto', models.ImageField(upload_to='mascota_centro_adopcion', verbose_name='Imagen')),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_adopcion.refugio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_adopcion.tipomascota')),
            ],
        ),
    ]
