# Generated by Django 5.2.6 on 2025-11-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.CharField(max_length=200)),
                ('info2', models.CharField(max_length=200)),
            ],
        ),
    ]
