# Generated by Django 5.2.6 on 2025-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_adopcion', '0002_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Centro de Adopción ❤️', max_length=100, verbose_name='Nombre del sitio')),
                ('mensaje_bienvenida', models.CharField(default='Dale un hogar a un nuevo amigo hoy ❤️', max_length=200, verbose_name='Mensaje de bienvenida')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración activa')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
        migrations.DeleteModel(
            name='Informacion',
        ),
    ]
